= Shear Force Software Team To-Do List:

== To prepare for first meet

- [x] AUTO: Integrate Pinpoint Odometry Driver
- [x] Add telemetry for pinpoint IMU and movement ticks to ShowTelemetry()
- [x] AUTO: Calibrate Gericka roadrunner
- [*] GENERAL - Experiment and Verify the new blackboard concept to store auto settings for manual usage

=== Shrey

- [x] AUTO(Shrey): Test Blue_Far_Auto for positions
- [x] AUTO(Shrey): Complete TODOs in Blue_Far_Auto to make shoot, intake, and track target
- [x] AUTO(Shrey): Create a Red_Far_Auto that mirrors Blue_Far_Auto
- [ ] AUTO: Test and tweak the two far auto routes to be awesome

=== Akshay

- [ ] AUTO(Akshay): Create a Blue_Close_Auto to shoot 3 (from big triangle), intake closest line, shoot 3, park safely
  * Need MeepMeep route, the ones currently in there don't do this simple meet 1 approach
  * Copy structure of the Blue_Far_Auto when ready so the code seems familiar to everyone
- [ ] AUTO(Akshay): Create a Red_Close_Auto to shoot 3, intake closest line, shoot 3, park safely

=== Tong

- [x] SHOOTER(Tong): use the data collected to create a CalculateOptimumShooterRPM(double distanceInInches) method
- [x] SHOOTER(Tong): create method to use the webcam distance-to-target to auto set the shooter target RPMs using the CalculateOptimumShooterRPM()
  * if (getAprilTagVisible(currentTargetId)) then CalculateOptimumShooterRPM(getDistanceToAprilTag(currentTargetId))
- [x] SHOOTER(Tong): need button to turn auto RPM mode setting on/off - default to on
  * look at TODOs in Manual control class
- [ ] Test all buttons, make them all work (fix the if && logic )
- [ ] Test shooting the balls
- [x] Develop method that can calculate distance between two points (will use with pinpoint to take current position to goal without relying on camera)
- [x] Develop method to calculate turn angle needed for turret to point at goal given two points and current heading (will use with pinpoint without relying on camera)

=== Gianna

- [x] GENERAL(Gianna) - Setup the control hub and driver station wifi to pass inspection
  * Run the Self-Inspect
    ** https://ftc-docs.firstinspires.org/en/latest/hardware_and_software_configuration/self_inspect/new-self-inspect.html
  * Need to make sure ALL of our driver HUBs are loaded with the latest firmware from Rev Hardware Client
  * Need to make sure our WiFi name and password are legal
    ** pword: ShearForce21225SF
- [x] LIFTER(Gianna): Integrate logic to use the ball distance detection sensor to automatically lift ball half way towards shooter
  * if (lifter is down && (ball detected by sensor-1 || ball detected by sensor-2)) then lift ball half-way up
  * Need to figure out which exact sensor is installed Rev Color V2, Rev Color V3, or Rev 2M Distance
  * Example code for any of those sensors can be found on the Rev site around here:
    ** https://docs.revrobotics.com/rev-crossover-products/sensors/2m-distance/application-examples#onbot-java
- [ ] LIFTER(Gianna): need combo button to turn auto lifter logic on/off - default to on
  * look at TODOs in Manual control class
- [ ] INTAKE: Integrate logic to use the ball distance detection sensors to turn intake on/off automatically
  * if (inside sensor says empty && outside sensor ball present) then turn intake on
  * else if (inside sensor says ball present) then turn intake off
  * Example code for sensor is at:
    ** FtcRobotController -> external.samples -> SensorDigitalTouch
- [ ] INTAKE: need combo button to turn auto intake logic on/off - default to on
  * look at TODOs in Manual control class

== Next Level Stuff

- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color
- [ ] Integrate April tag detection to the Autonomous routes, change intake based on detected
- [ ] Setup PID controller for shooter motors
- [ ] Setup PID controller for turret rotator
- [ ] Develop lots of autonomous options and test them
- [ ] AUTO: Implement Blue Large triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red Large triangles start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Blue small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices


== Advanced Shooter System Tasks

- [ ] Develop function to calculate the optimum launcher ramp height

== Color Sensor / LED Tasks

- [ ] Develop test program to assess color sensor usage on balls, document best color ranges to use
- [ ] Integrate the new LED light system

== Setup Laptops and Accounts

- [ ] Verify Shrey has his laptop setup correctly

== Odometry Assessment Related Tasks

- [ ] Calibrate Summer Chassis
- [ ] Develop a test path plan to use to assess odometry pods
- [ ] Conduct tests of the different odometry pods and compare results


