= Shear Force Software Team To-Do List:

== To prepare for first meet

- [ ] LIFTER: Add small offset to bottom of lifter to prevent dragging on floor
- [ ] LIFTER: Add a half way position, that could be commanded that lifts ball up so more room, without lifting so high that it shoots (will trigger later based on sensors)
- [ ] LIFTER: Change logic to auto return to bottom after lifting up to shooter
- [ ] SHOOTER: Verify shooter motor directions are correct in code
- [ ] SHOOTER: Verify shooter RPM calculation (check the ticks from manufacturer, not sure using correct motor constant)
- [ ] SHOOTER: Create a method to set the velocity of the shooter motors based on desired RPMs
- [ ] SHOOTER: Test shooter using different RPMs and different friction walls, document to determine best choice
- [ ] TURRET: Test and verify if changes are needed to manual turret control
- [ ] TURRET: Test using webcam to control turret auto tracking
- [ ] TURRET: Add gamepad controller method to turn auto tracking on/off
- [ ] AUTO: Calibrate Gericka roadrunner
- [ ] AUTO: Implement at least one autonomous route for Red side, that can shoot 3 pre-loaded balls
- [ ] AUTO: Implement at least one autonomous route for Blue side, that can shoot 3 pre-loaded balls
- [*] Experiment and Verify the new blackboard concept to store auto settings for manual usage
- [ ] Setup the control hub and driver station wifi to pass inspection

== Next Level Stuff

- [ ] Integrate April tag detection to the Autonomous routes, change intake based on detected
- [ ] Setup PID controller for shooter motors
- [ ] Setup PID controller for turret rotator
- [ ] Develop lots of autonomous options and test them

== Advanced Shooter System Tasks

- [ ] Develop function to convert distance + angle to launch speed
- [ ] Develop function to calculate the optimum launcher ramp height

== Color Sensor / LED Tasks

- [ ] Develop test program to assess color sensor usage on balls, document best color ranges to use
- [ ] Integrate the new LED light system

== Setup Laptops and Accounts

- [ ] Verify Shrey has his laptop setup correctly

== Odometry Assessment Related Tasks

- [ ] Calibrate Summer Chassis
- [ ] Develop a test path plan to use to assess odometry pods
- [ ] Conduct tests of the different odometry pods and compare results


