= Shear Force Software Team To-Do List:

== Tasks to be worked

=== Akshay

- [ ] AUTO: find how fast we run the auto routines by experimenting with velocity constraints
- [ ] AUTO: create a new 12 ball shooter Far Auto opmode
- [ ] AUTO: create a new 9-12 ball shooter Close Auto opmode

=== Gianna

- [ ] AUTO: Test and update the 2 close autos, probably need to set ramp and speeds to align with new shooter table
- [ ] TURRET: Start creating logic for the limit switches - will use to do some resets...

=== Shrey

- [ ] AUTO: Test auto opmodes to use the correct PIDF values
- [ ] AUTO: Add new theRobot.RunAutoIntake() method to Second thread in an auto routine
  * remove manual intake on/off commands in the auto opMode, then test if works effectively, if it does make all autos do it
  * be sure to put inside a check that run has been started (don't want auto intake running during init)
- [ ] AUTO: Experiment with lowering sleep time for lifterUp, should be able to do 250 milliseconds
- [ ] AUTO: Experiment with lowering sleep time for lifterDown

=== Tong

- [ ] SHOOTER: experiment with Shoot3 function to make faster, use dashboard to change sleep times to test faster
- [ ] TURRET: SLAMMING - how can we eliminate?  Maybe try a lower power setting?  Maybe only a lower power setting when change is more than 90 degrees?
- [ ] TURRET: Can we make it track smoother? Maybe a PIDF solution?

== Next Stuff

- [ ] Create function that can report true/false IF robot is in a legal shooting tile
- [ ] Create an auto shoot mode that can be turned on/off that will shoot if in a legal shooting tile and a ball is loaded
- [ ] AUTO: create an auto that gets and shoots multiple lines in the correct pattern order
- [ ] Create a common blackboard position storage routine in Hardware class, that the auto methods can call after every move, so if crashes on next move, the position is hopefully correct for manual usage
- [ ] Have manual write position to blackboard periodically when in a stopped web-cam verified location?  (So can start and restart manual better)
- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color




