= Shear Force Software Team To-Do List:

== Tasks to be worked

=== Akshay

- [ ] Test and update the 2 close autos, probably need to set ramp and speed to align with new shooter table

=== Gianna

- [ ] Make manual turret controls work with gamepad2.right_stickX (so easier to manually fix turret)
  * Can leave existing controls in place too, make it an OR condition
- [ ] Change RunAutoIntake() to use a special sleep instead of a regular sleep, test it
- [ ] Add beambreak3 to lifter logic

=== Shrey

- [ ] AUTO: Add new theRobot.RunAutoIntake() method to Second thread in an auto routine
  * remove manual intake on/off commands in the auto opMode, then test if works effectively, if it does make all autos do it
  * be sure to put inside a check that run has been started (don't want auto intake running during init)
- Tune built-in PIDF using dashboard to achieve faster recovery without overshoots
  * Run Manual - put notes in comments of SetShooterPIDFCoefficients()
    ** [x] RECORD velocity and power values for small triangle position
    ** [ ] RECORD velocity and power values for AUTO Close position
    ** [x] RECORD current PIDF values from telemetry
  * Run Manual with DASHBOARD connected from small triangle position
    ** [ ] In Dashboard, change **shooterPIDF_Enabled** to be true
    ** [ ] Change **shooterF** to be 80% of velocity value for small triangle shot above
    ** [ ] Increase **shooterP** slowly until motor velocity starts to oscillate around target velocity
    ** [ ] Increase **shooterD** slowly to eliminate overshoot and minimize oscillations
    ** [ ] If velocity staying under target velocity, slowly increase **shooterI** until gets to target without significantly overshooting
    ** [ ] Tweak the 3 values until happy with shot recovery and spin up at small triangle location
    ** [ ] RECORD the 4 values in comments in SetShooterPIDFCoefficients(), change the defaults to match
  * [ ] Repeat the dashboard tuning process at the close up shooting position, determine if there is should be a second set of coefficients stored that could be swapped back and forth, or if the small triangle ones are sufficient for close up too
  * [ ] if PIDF seems effective, turn on for auto and remove the spin up while loops and RETEST

- [ ] AUTO: Experiment with lowering sleep time for lifterUp, should be able to do 250 milliseconds
- [ ] AUTO: Test, test, test -- need all 3 balls to shoot consistently every time, and all balls to be ingested
- [ ] AUTO: Experiment with lowering sleep time for lifterDown

=== Tong

- [ ] Get the turret limits working correctly
- [ ] Experiment with uncommenting the "use april tag bearing" portion of adjustTurretToTargetAprilTag() to make it correct the bearing faster when in error state

== Next Level Stuff

- [ ] Create a common blackboard position storage routine in Hardware class, that the auto methods can call after every move, so if crashes on next move, the position is maybe correct for manual usage
- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color
- [ ] Develop lots of autonomous options and test them
- [ ] Increase speed of robot in autonomous




