= Shear Force Software Team To-Do List:

== Tasks to be worked

- [ ] AUTO: Create a 9 ball FAR opMode (from 12 ball far)
- [ ] AUTO: Create a 9 ball CLOSE opMode
- [ ] AUTO: Create a 12 ball CLOSE opMode
- [ ] AUTO: Create a 3 + 9 FAR opMode (release the gate after shoot 3)
- [ ] AUTO: Create a 3 + 9 CLOSE opMode (release the gate after shoot 3)

=== Akshay

- [ ] AUTO: Get 12 ball FAR shooting 12 consistently
- [ ] Start deciding what we should share about our programming and control capabilities with judges

=== Gianna

- [ ] AUTO: Get 6 ball close Auto opModes working again
- [ ] TURRET: Start creating logic for the limit switches - will use to do some resets...
- [ ] Start deciding what we should share about our programming and control capabilities with judges

=== Shrey

- [ ] Start deciding what we should share about our programming and control capabilities with judges

=== Tong

- [ ] Start deciding what we should share about our programming and control capabilities with judges

== Next Stuff

- [ ] Create function that can report true/false IF robot is in a legal shooting tile
- [ ] Create an auto shoot mode that can be turned on/off that will shoot if in a legal shooting tile and a ball is loaded
- [ ] AUTO: create an auto that gets and shoots multiple lines in the correct pattern order
- [ ] Create a common blackboard position storage routine in Hardware class, that the auto methods can call after every move, so if crashes on next move, the position is hopefully correct for manual usage
- [ ] Have manual write position to blackboard periodically when in a stopped web-cam verified location?  (So can start and restart manual better)
- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color




