= Shear Force Software Team To-Do List:

== Tasks to be worked

- [ ] PRIORITY: we slowed down the lifter up down sleeps on 1/20 (from 175/350 to 300/450) to ensure 3 ball shoot was working, need to see how fast we can move back down to and still have auto shoot 3 balls work correctly
- [ ] PRIORITY: new threading added to Manual, Blue 12, and Red 12 to allow for auto intake to run during shoot 3, need to test and verify all 3 still working
- [ ] PRIORITY: fix any remaining issues with Blue 12 and Red 12 preventing accuracy

=== Akshay

- [ ] AUTO: create a new 12 ball shooter with bridge clearing Far Auto opmode
- [ ] Start deciding what we should share about our programming and control capabilities with judges

=== Gianna

- [ ] AUTO: Create a new Auto mode to give us more options
- [ ] TURRET: Start creating logic for the limit switches - will use to do some resets...
- [ ] Start deciding what we should share about our programming and control capabilities with judges

=== Shrey

- [ ] AUTO: Create a new Auto mode to give us more options
- [ ] Start deciding what we should share about our programming and control capabilities with judges

=== Tong

- [ ] AUTO: Create a new Auto mode to give us more options
- [ ] TURRET: keeps getting off, what is causing that, how can we fix?
- [ ] Start deciding what we should share about our programming and control capabilities with judges

== Next Stuff

- [ ] Create function that can report true/false IF robot is in a legal shooting tile
- [ ] Create an auto shoot mode that can be turned on/off that will shoot if in a legal shooting tile and a ball is loaded
- [ ] AUTO: create an auto that gets and shoots multiple lines in the correct pattern order
- [ ] Create a common blackboard position storage routine in Hardware class, that the auto methods can call after every move, so if crashes on next move, the position is hopefully correct for manual usage
- [ ] Have manual write position to blackboard periodically when in a stopped web-cam verified location?  (So can start and restart manual better)
- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color




