= Shear Force Software Team To-Do List:

== To prepare for first meet

- [*] LIFTER: Add small offset to bottom of lifter to prevent dragging on floor
- [*] LIFTER: Add a half way position, that could be commanded that lifts ball up so more room, without lifting so high that it shoots (will trigger later based on sensors)
- [*] LIFTER: Change logic to auto return to bottom after lifting up to shooter
- [ ] SHOOTER: Verify shooter motor directions are correct in code
- [ ] SHOOTER: Verify shooter RPM calculations working, record max, should be around 5400 RPM, theoretically could be up to 6000 RPM, record average RPMs at 100% power, 50% power, 25% power, and 75% power.  Record AMP pull of motors too.
- [ ] SHOOTER: Create a method to set the velocity of the shooter motors based on desired RPMs, test and see how well it holds that RPM
- [ ] SHOOTER: Test shooter using different RPMs and different friction walls, document to determine best choice
- [ ] TURRET: Test and verify if changes are needed to manual turret control or if now using correct tick calculations (will need to disconnect shooter wires if wire management not fully implemented yet)
- [ ] TURRET: Test using webcam to control turret auto tracking
- [ ] TURRET: Add gamepad controller method to turn auto tracking on/off
- [ ] TURRET: Probably need a gamepad controller method to switch alliance colors (and targets)
- [ ] AUTO: Calibrate Gericka roadrunner
- [ ] AUTO: Implement at least one autonomous route for Red Large Triangle side, that can shoot 3 pre-loaded balls, and park - (no camera needed)
- [ ] AUTO: Implement at least one autonomous route for Blue Large Triangle side, that can shoot 3 pre-loaded balls, and park - (no camera needed)
- [ ] AUTO: Implement one auto route for Red Small Triangle that shoots 3 pre-loaded balls and then parks safely - (no camera needed)
- [ ] AUTO: Implement one auto route for Blue Small Triangle that shoots 3 pre-loaded balls and then parks safely - (no camera needed)
- [*] Experiment and Verify the new blackboard concept to store auto settings for manual usage
- [ ] Setup the control hub and driver station wifi to pass inspection

== Next Level Stuff

- [ ] Integrate logic to use the ball distance detection sensors to turn intake on/off automatically
- [ ] Integrate logic to use the ball distance detection sensor to automatically lift ball half way towards shooter
- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color
- [ ] Integrate April tag detection to the Autonomous routes, change intake based on detected
- [ ] Setup PID controller for shooter motors
- [ ] Setup PID controller for turret rotator
- [ ] Develop lots of autonomous options and test them
- [ ] AUTO: Implement Blue Large triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red Large triangles start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Blue small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices


== Advanced Shooter System Tasks

- [ ] Develop function to convert distance + angle to launch speed
- [ ] Develop function to calculate the optimum launcher ramp height

== Color Sensor / LED Tasks

- [ ] Develop test program to assess color sensor usage on balls, document best color ranges to use
- [ ] Integrate the new LED light system

== Setup Laptops and Accounts

- [ ] Verify Shrey has his laptop setup correctly

== Odometry Assessment Related Tasks

- [ ] Calibrate Summer Chassis
- [ ] Develop a test path plan to use to assess odometry pods
- [ ] Conduct tests of the different odometry pods and compare results


