= Shear Force Software Team To-Do List:

== Tasks to be worked

=== PRIORITY TASKS (anyone can do)

- [ ] TEST new manual auto shooter + auto launch ramp values (drive around and shoot)
  * Can adjust CalculateOptimumLaunchRampPosition() and/or CalculateOptimumShooterRPM() if needed

=== Akshay

- [ ] Test Red Far Obelisk for accuracy of shots
- [ ] Test Blue Far Obelisk for accuracy of shots
- [ ] Test and update the 2 close autos, probably need to set ramp and speed to align with new shooter table

=== Gianna

- [x] Parking Stand Servos Integration
  1. Add 2 new servos to config file (control hub, ports 2 and 3)
  2. Add the 2 new servos to Gericka_Hardware::Init() method
  3. Print out the current position of the 2 servos in the ShowTelemetry() routine
  4. Add max and min limits of (max = 0.3, min = 0.0) for the new servos
  5. Create a method in the HW class to set the servo to a position, limit to max and min
  6. Add 2 buttons on Gamepad1 to command the parking stand position to the two positions
  7. TEST it
- [x] Separate the resetTurretAndPosition() from the resetYaw logic.
  1. Connect theRobot.resetPositionToZero to (gamepad1.dpadUp + options),
  2. Connect theRobot.resetTurret to (gamepad2.square + options)
  2. Make the resetTurretAndPosition() harder to accidentally do (gamepad1.triangle + share)
  3. Make triangle only back to just doing a resetYaw
- [ ] Make manual turret controls work with gamepad2.right_stickX (so easier to manually fix turret)
  * Can leave existing controls in place too, make it an OR condition

=== Shrey

- [ ] AUTO: Add new theRobot.RunAutoIntake() method to Second thread in an auto routine
  * remove manual intake on/off commands in the auto opMode, then test if works effectively, if it does make all autos do it
  * be sure to put inside a check that run has been started (don't want auto intake running during init)
- Tune built-in PIDF using dashboard to achieve faster recovery without overshoots
  * Run Manual - put notes in comments of SetShooterPIDFCoefficients()
    ** [x] RECORD velocity and power values for small triangle position
    ** [ ] RECORD velocity and power values for AUTO Close position
    ** [x] RECORD current PIDF values from telemetry
  * Run Manual with DASHBOARD connected from small triangle position
    ** [ ] In Dashboard, change **shooterPIDF_Enabled** to be true
    ** [ ] Change **shooterF** to be 80% of velocity value for small triangle shot above
    ** [ ] Increase **shooterP** slowly until motor velocity starts to oscillate around target velocity
    ** [ ] Increase **shooterD** slowly to eliminate overshoot and minimize oscillations
    ** [ ] If velocity staying under target velocity, slowly increase **shooterI** until gets to target without significantly overshooting
    ** [ ] Tweak the 3 values until happy with shot recovery and spin up at small triangle location
    ** [ ] RECORD the 4 values in comments in SetShooterPIDFCoefficients(), change the defaults to match
  * [ ] Repeat the dashboard tuning process at the close up shooting position, determine if there is should be a second set of coefficients stored that could be swapped back and forth, or if the small triangle ones are sufficient for close up too
  * [ ] if PIDF seems effective, turn on for auto and remove the spin up while loops and RETEST

- [ ] AUTO: Experiment with lowering sleep time for lifterUp, should be able to do 250 milliseconds
- [ ] AUTO: Test, test, test -- need all 3 balls to shoot consistently every time, and all balls to be ingested
- [ ] AUTO: Experiment with lowering sleep time for lifterDown

=== Tong

- [ ] AUTO: develop and test an auto to get the 3 balls on the wall
- [ ] AUTO: develop and test an auto to shoot 3 balls, pick up 3 on wall and shoot them, pick up correct line, release the gate, then shoot 3 balls

== Next Level Stuff

- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color
- [ ] Develop lots of autonomous options and test them




