= Shear Force Software Team To-Do List:

== To prepare for first meet

- [x] AUTO: Integrate Pinpoint Odometry Driver
- [x] Add telemetry for pinpoint IMU and movement ticks to ShowTelemetry()
- [x] AUTO: Calibrate Gericka roadrunner
- [ ] AUTO: Test Blue_Far_Auto for positions
- [ ] AUTO: Complete TODOs in Blue_Far_Auto to make shoot, intake, and track target
- [ ] AUTO: Create a Red_Far_Auto that mirrors Blue_Far_Auto
- [ ] AUTO: Create a Blue_Close_Auto to shoot 3, intake closest line, shoot 3, park safely
- [ ] AUTO: Create a Red_Close_Auto to shoot 3, intake closest line, shoot 3, park safely
- [ ] SHOOTER: use the data collected to create a CalculateOptimumShooterRPM(double distanceInInches) method
- [ ] SHOOTER: use the new webcam distance to target to auto set the shooter target RPMs
  * if (getAprilTagVisible(currentTargetId)) then CalculateOptimumShooterRPM(getDistanceToAprilTag(currentTargetId))
- [ ] SHOOTER: need button to turn auto RPM mode setting on/off - default to on
- [*] Experiment and Verify the new blackboard concept to store auto settings for manual usage
- [ ] Setup the control hub and driver station wifi to pass inspection
- [ ] LIFTER: Integrate logic to use the ball distance detection sensor to automatically lift ball half way towards shooter
* if (lifter is down && (ball detected by sensor-1 || ball detected by sensor-2)) then lift ball half-way up
- [ ] LIFTER: need combo button to turn auto lifter logic on/off - default to on

== Next Level Stuff

- [ ] INTAKE: Integrate logic to use the ball distance detection sensors to turn intake on/off automatically
  * if (inside sensor says empty && outside sensor ball present) then turn intake on
  * else if (inside sensor says ball present) then turn intake off
- [ ] INTAKE: need combo button to turn auto intake logic on/off - default to on


- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color
- [ ] Integrate April tag detection to the Autonomous routes, change intake based on detected
- [ ] Setup PID controller for shooter motors
- [ ] Setup PID controller for turret rotator
- [ ] Develop lots of autonomous options and test them
- [ ] AUTO: Implement Blue Large triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red Large triangles start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Blue small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices


== Advanced Shooter System Tasks

- [ ] Develop function to calculate the optimum launcher ramp height

== Color Sensor / LED Tasks

- [ ] Develop test program to assess color sensor usage on balls, document best color ranges to use
- [ ] Integrate the new LED light system

== Setup Laptops and Accounts

- [ ] Verify Shrey has his laptop setup correctly

== Odometry Assessment Related Tasks

- [ ] Calibrate Summer Chassis
- [ ] Develop a test path plan to use to assess odometry pods
- [ ] Conduct tests of the different odometry pods and compare results


