= Shear Force Software Team To-Do List:

== Tasks to be worked


=== Akshay

- [ ] AUTO: Create a Blue_Close_Auto to shoot 3 (from big triangle), intake closest line, shoot 3, park safely
- [ ] AUTO: Create a Red_Close_Auto to shoot 3, intake closest line, shoot 3, park safely
- [ ] AUTO: Read the obelisk and set a variable for what pattern is being shown

=== Gianna

- [ ] INTAKE: Integrate logic to use the ball distance detection sensors to turn intake on/off automatically
* if (inside sensor says empty && outside sensor ball present) then turn intake on
* else if (inside sensor says ball present) then turn intake off
* Example code for sensor is at:
** FtcRobotController -> external.samples -> SensorDigitalTouch
- [ ] INTAKE: need combo button to turn auto intake logic on/off - default to on
* look at TODOs in Manual control class
- [ ] move the auto mode variables from Manual class to Hardware class, so can put all of them in the telemetry, to make testing buttons to turn auto functions on/off easier
- [ ] Test all buttons, make them all work, in particular it appears a lot of the SHARE + buttons are not working correctly

=== Shrey

- [ ] AUTO: Change far auto routine to be separate path calls, so that shooting can be handled outside of actions (look at Blue_Close_Auto for example of separate path calls with shooting separate), this will give us more flexibility to use variables to control the sleep times between shots, and to use time to decide if we shoot more balls or not
- [ ] AUTO: Change the ending to be time based, meaning if we have enough time, lets shoot another 3 balls then park
  * Example:
```
   Gericka_Hardware.autoTimeLeft = 30 - getRuntime();
   if (Gericka_Hardware.autoTimeLeft > 10) {  //TODO calculate time needed to shoot 3 and park
      Actions.runBlocking(new ParallelAction(DriveFirstMarkToSmallTriangle, setIntakeOff()));

      // Shoot 3 balls here

      // Drive to parking spot...
   }
```

=== Tong

- [ ] Retest pinpoint telemetry during Auto (switched from resetPosAndIMU to just recalibrateIMU) -- is it correct now?
- [ ] Retest pinpoint telemetry during teleop after Auto -- does it start at same reported position as auto finished in, does it stay correct?
- [ ] IF pinpoint still not reporting correct values, then create variable to store initial position in HW class, then create method(s) to get pinpoint position + initial offsets, convert telemetry to use these new values, and test.  Then can use for turret logic.
- [ ] Disable the April tag update of pinpoint position for now
- [ ] Test tracking of target with pinpoint

== Next Level Stuff

- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color
- [ ] Integrate April tag detection to the Autonomous routes, change intake order based on detected april tag
- [ ] Develop lots of autonomous options and test them
- [ ] AUTO: Implement Blue Large triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red Large triangles start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Blue small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices


== Advanced Shooter System Tasks

- [ ] Develop function to calculate the optimum launcher ramp height
- [ ] Setup PID controller for shooter motors
- [ ] Setup PID controller for turret rotator


