= Shear Force Software Team To-Do List:

== Tasks to be worked


=== Akshay

- [x] AUTO: Create a Blue_Close_Auto to shoot 3 (from big triangle), intake closest line, shoot 3, park safely
- [ ] AUTO: Create a Red_Close_Auto to shoot 3, intake closest line, shoot 3, park safely
- [ ] AUTO: Read the obelisk and set a variable for what pattern is being shown
- [ ] AUTO: Limit when intake motor is on to only when needed for the close autos

=== Gianna

- [ ] INTAKE: Integrate logic to use the ball distance detection sensors to turn intake on/off automatically
* if (inside sensor says empty && outside sensor ball present) then turn intake on
* else if (inside sensor says ball present) then turn intake off
* Example code for sensor is at:
** FtcRobotController -> external.samples -> SensorDigitalTouch
- [ ] Test all buttons, make them all work, in particular it appears a lot of the SHARE + buttons are not working correctly

=== Shrey

- [ ] AUTO: Experiment with lowering sleep time for lifterUp, should be able to do 250 milliseconds
- [ ] AUTO: Test, test, test -- need all 3 balls to shoot consistently every time, and all balls to be ingested
- [ ] AUTO: Experiment with lowering sleep time for lifterDown

=== Tong

- [ ] Test tracking of target to set turret rotation angle with pinpoint absolute values for the calculation

== Next Level Stuff

- [ ] Integrate logic to use the ball distance detection sensor to detect the loaded ball color and change an indicator light to that color
- [ ] Integrate April tag detection to the Autonomous routes, change intake order based on detected april tag
- [ ] Develop lots of autonomous options and test them
- [ ] AUTO: Implement Blue Large triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red Large triangles start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Blue small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices
- [ ] AUTO: Implement Red small triangle start that can shoot 3 balls, and pick up correct line and shoot them then park for any of the 3 choices


== Advanced Shooter System Tasks

- [ ] Develop function to calculate the optimum launcher ramp height
- [ ] Setup PID controller for shooter motors
- [ ] Setup PID controller for turret rotator


